name: dscript
description: Scripting language for flutter/dart plugins & extensions
version: 1.0.0
repository: https://github.com/mcquenji/dscript

environment:
  sdk: ^3.5.4

dependencies:
  equatable: ^2.0.7
  logging: ^1.3.0
  meta: ^1.17.0
  pub_semver: ^2.2.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
