name: dscript_dart
description: Scripting language for flutter/dart plugins & extensions
version: 1.0.1
repository: https://github.com/mcquenji/dscript

environment:
  sdk: ^3.5.4

dependencies:
  antlr4: ^4.13.2
  collection: ^1.19.1
  equatable: ^2.0.7
  logging: ^1.3.0
  meta: ^1.17.0
  pub_semver: ^2.2.0
  result_dart: ^2.1.0
  stack: ^0.2.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
