name: dscript
description: Scripting language for flutter/dart plugins & extensions
version: 1.0.0
repository: https://github.com/mcquenji/dscript

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
# dependencies:
# path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
