on:
  push:
    branches:
      - main
    tags-ignore: 
      - 'v*.*.*' # Ignore version tags so we dont recursively run this workflow
    paths-ignore:
      - 'CHANGELOG.md'
      - 'pubspec.yaml'
  workflow_dispatch:
      
jobs:
    bump-version:
      permissions:                
        contents: write           
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4.2.2

        - uses: actions/setup-node@v4
        - name: Install absolute version
          run: npm i -g commit-and-tag-version

        - name: Bump version
          run: |
            commit-and-tag-version
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}
            tags: true
            
    publish:
        needs: bump-version
        permissions:
            id-token: write # Required for authentication using OIDC
        uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1